version: '3.8'

services:
  api:
    build:
      context: .
    container_name: webscraper-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  dashboard:
    image: python:3.11-slim
    container_name: webscraper-dashboard
    working_dir: /dashboard
    command: streamlit run main.py --server.port 8501 --server.enableCORS false
    volumes:
      - ./dashboard:/dashboard
      - ./logs:/logs
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    tty: true
    stdin_open: true
